### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by DilumAluthge** [alan-turing-institute/ScientificTypes.jl#103]
I'm opening this issue to track what issues and/or pull requests are blocking for a 1.0 release of ScientificTypes.

cc: @ablaom 
cc: @tlienart

**Comment by DilumAluthge** [comment]
Bump @ablaom @tlienart 

Are there any breaking changes that you want to make to the public API of ScientificTypes.jl before releasing ScientificTypes.jl version 1.0?

**Comment by tlienart** [comment]
I don't think breaking changes to the API should be expected, we may add stuff (e.g. #102) or fix stuff (as in #108) but otherwise we could release 1.0 I think. @ablaom your call though 🙂

**Comment by DilumAluthge** [comment]
Bump @tlienart @ablaom Any further thoughts on this. Since ScientificTypes.jl is a direct or indirect dependency of any package that implements the MLJ model interface, it would be great to move towards a 1.0 release.

**Comment by ablaom** [comment]
Yes I am looking into this today.
