### ISSUE TITLE
Temporal data - scalar types

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#14]
Should there be additional type(s) for time series data?

**Comment by ablaom** [comment]
Probably we need two types. I think the reasoning for having two *machine* types in Julia carries over to the *scientific* case:

> The Dates module provides two types for working with dates: Date and DateTime, representing day and millisecond precision, respectively; both are subtypes of the abstract TimeType. The motivation for distinct types is simple: some operations are much simpler, both in terms of code and mental reasoning, when the complexities of greater precision don't have to be dealt with. For example, since the Date type only resolves to the precision of a single date (i.e. no hours, minutes, or seconds), normal considerations for time zones, daylight savings/summer time, and leap seconds are unnecessary and avoided.

So, Julia has `Date` and `DateTime` subtyping `TimeType`. What should the scientific types be called? The names should be different to allow both machine types and scitypes to be in scope at the same time.

- option 1: `Day` and `Instant` subtyping `Time` (elegant)
- option 2: `DateScitype` and `DateTimeScitype` subtyping `TimeScitype` (ugly as sin,  but easier to remember if you know the machine types)
- option 3: ?

**Comment by ablaom** [comment]
Okay, while I have merged a PR for option 1, I'm still not completely happy with this. 

1. I have overlooked the Julia type `Time` for time within 24hr day. So the complete list of julia native concrete subtypes of `TimeType` is:

- `DateTime` - for any historical time
- `Time` - for time within the 24hr day 
- `Date` - for a date

2. The name `Day` for the scitype corresponding to a date conflicts with the julia type `Day` for a time *interval* of 24 hours. 

I should like the input of time series experts on whether, like the julia native machine types, just three distinctions from the "scientific type" perspective should also suffice.

cc: @fkiraly @mloning

**Comment by ablaom** [comment]
Okay, not getting a lot of feedback here, so I expect no-one is bothered one way or the other. 

So in analogy with the Julia  

```julia
TimeType
├─ Date
├─ Time
└─ DateTime
```

we'll do

```Julia
ScientificTimeType
├─ ScientificDate
├─ ScientificTime
└─ ScientificDateTime
```
