### ISSUE TITLE
Coercion of non-categorical vectors into Finite

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#21]
I believe this to be a bug but it could also be a misunderstanding:

### Expected behaviour

```julia
using ScientificTypes, DataFrames
X = DataFrame(a = [1, 2, 3, missing], b =['m','f','m',missing])
Xc = coerce(X, :a=>OrderedFactor, :b=>Multiclass)
schema(Xc).scitypes
```

This will give

```
(Union{Missing, OrderedFactor{3}}, Union{Missing, Multiclass{2}})
```

### The problem

Let's do this **without** DataFrames

```julia
using ScientificTypes, Tables
X = (a = [1, 2, 3, missing], b =['m','f','m',missing])
Xc = coerce(X, :a=>OrderedFactor, :b=>Multiclass)
```

This throws

```
no method matching coerce(::Array{Union{Missing, Int64},1}, ::Type{OrderedFactor}; verbosity=1)
```

(and it stops there but would also throw that it can't coerce a Vector of char into multiclass)

### A solution

Define a coercion for those things; I believe this would require using `categorical` first and then the coercion.

By the way `categorical(categorical(...))` is a no-op as far as I can tell, so it wouldn't be an issue to just do `categorical` systematically and it would just not apply if it's already been done before like in a DataFrame

**Comment by ablaom** [comment]
Okay, strictly speaking this is not a bug, but it evidently a likely cause for confusion. 

One cannot coerce a vector to `Finite` unless CategoricalArrays has been imported, because CategoricalArrays is an optional dependency of `ScientificTypes`. Since DataFrames requires CategoricalArrays, this isn't a problem in you first example, but it is in the second.

Remedies:

1. Make `CategoricalArrays` an explicit dependency (only a disadvantage for those who want a convention different from *mlj*)

2. Improve the documentation, starting with changing this example:

```julia
using DataFrames, Tables
X = DataFrame(
     name=["Siri", "Robo", "Alexa", "Cortana"],
     height=[152, missing, 148, 163],
     rating=[1, 5, 2, 1])
schema(X)
and so forth
```

To 

``` julia
using Tables, CategoricalArrays
X = (name=["Siri", "Robo", "Alexa", "Cortana"],
     height=[152, missing, 148, 163],
     rating=[1, 5, 2, 1])
schema(X)
etc
```

@tlienart What do you think?

**Comment by tlienart** [comment]
Thanks for the explanation, I’d be in favour of making CA an explicit dependency and maybe re-assessing if/when in the future more projects end up requiring ST and/or an alternative implementation of categoricals becomes available.

Though if you prefer the alternative, I don’t have a strong opinion, at the moment people would not use ScientificTypes in isolation and so would probably not be exposed to this issue very often.

My preference is with the dependency out of convenience but if you think it could cause compat issues or otherwise cause problems in the longer term, lets go with modifying the doc (which I’m happy to do)

**Comment by ablaom** [comment]
> Thanks for the explanation, I’d be in favour of making CA an explicit dependency and maybe re-assessing if/when in the future more projects end up requiring ST and/or an alternative implementation of categoricals becomes available.

This was my thought also. Let's just add the dependency. There's a small update in the docs where dependencies are mentioned that will also need updating. 

The [compat] bound for CategoricalArrays should be `CategoricalArrays = "<0.5.3, 0.7"`

I'm assigning you, @tlienart , but I might pick this up while I'm doing something else.

Thanks

**Comment by ablaom** [comment]
Resolved. Tables is now hard dep.
