### ISSUE TITLE
Extend coerce to arrays

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/ScientificTypes.jl#35]
The restriction to one-dimensional arrays was because we had tables in mind, but does not actually seem necessary.

**Comment by tlienart** [comment]
Could you maybe clarify the use case? coercion is done column by column isn't it?

**Comment by ablaom** [comment]
At present I can call coerce on a AbstractVector, as in 

```julia
coerce([1, 2, 3], Continuous)
```
But I cannot do the same for other arrays, eg:

```julia
coerce([1 2; 3 4], Conintuous)
```

And the only reason is because of an unecessarily restrictive type annotation on the first method.
