### ISSUE TITLE
Allow autotype on AbstractArray

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#47]
It will have to be another function with similar but different internals as there is no schema for an AbstractArray. The rest should look broadly similar.

**Comment by ablaom** [comment]
This is a bit strange, as I imagined that the table case is built on methods applied one column at-a-time. And the column methods, which act on vectors, could presumably be applied  unaltered to arrays. But maybe I'm missing something here.
