### ISSUE TITLE
add a coerce! function

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#50]
given that we often do `X = coerce(X, ...)` maybe it'd be good to just provide a `coerce!` which does that?

**Comment by ablaom** [comment]
I agree. Probably a dumb question:  How does this work given that arbitrary tables (eg, CSV file) cannot be mutated in place?

**Comment by tlienart** [comment]
oh  I didn't think about doing anything really  clever, this works:

```julia
coerce!(X, args...) = (X = coerce(X, args...))
```

it's maybe a bit misleading in that it's not an in-place modification, rather it just discards  the original object and makes a modified copy with the  name of the old object. I guess you wouldn't want to do that with very large data though.

There could also be overloading depending on `X`, for instance if `X` is a DataFrame then you  can actually modify columns in place. What do you think? I mean at the moment we do  copies anyway so...

**Comment by ablaom** [comment]
Sorry, I have to smile 😄 

```julia
julia> foo(v) = 2v
foo (generic function with 1 method)

julia> foo!(v) = (v = foo(v))
foo! (generic function with 1 method)

julia> v=[1, 1]
2-element Array{Int64,1}:
 1
 1

julia> foo!(v)
2-element Array{Int64,1}:
 2
 2

julia> v
2-element Array{Int64,1}:
 1
 1
```

**Comment by tlienart** [comment]
Yes that was silly, one more reason not to try to code too late... 

So the  way  forward I guess is that we could have a `coerce!` function that works on

* AbstractArray
* DataFrame

and specify  that in the doc; the risk is that it could be confusing and people might try on different things and not like the error. Maybe a  way around this is to also implement a  `coerce!` for everything else that does nothing but display an informative warning message suggesting that the user uses a DataFrame?

**Comment by ablaom** [comment]
I would prefer more clear-cut behaviour. The method should work or throw an error:

```julia
# fallback:
`coerce!`(X::Any) = throw(ArgumentError(("In place coercion not supported for $(typeof(X)). Try `coerce` instead. "))
# dataframes:
`coerce!(X::DataFrame) = ...
```
