### ISSUE TITLE
Scitypes for probabilities/odds

### ISSUE THREAD

**Issue by jpfairbanks** [alan-turing-institute/ScientificTypes.jl#69]
Would a scitype for probabilities make sense? I’m thinking the output of a binary classifier like logistic regression are probabilities over the two classes. This package seems like a good place to define that concept.

**Comment by tlienart** [comment]
Hello! Are you aware of the `UnivariateFinite` type defined  in MLJBase? this is what we use for probabilistic outputs such as classification with logistic / multinomial etc. Consider for instance these lines which I took from the tests:

```julia
julia> y = [  0,   0,   0,   1,   0,   1,   1,   0]  |> categorical;
julia> s = [0.0, 0.1, 0.1, 0.1, 0.2, 0.2, 0.5, 0.5];
julia> ŷ = [UnivariateFinite(classes(y[1]), [1.0-p, p]) for p in s]
8-element Array{UnivariateFinite{Int64,UInt32,Float64},1}:
 UnivariateFinite(0=>1.0, 1=>0.0)
 UnivariateFinite(0=>0.9, 1=>0.1)
 UnivariateFinite(0=>0.9, 1=>0.1)
 UnivariateFinite(0=>0.9, 1=>0.1)
 UnivariateFinite(0=>0.8, 1=>0.2)
 UnivariateFinite(0=>0.8, 1=>0.2)
 UnivariateFinite(0=>0.5, 1=>0.5)
 UnivariateFinite(0=>0.5, 1=>0.5)
```

**Comment by jpfairbanks** [comment]
I was not aware of that type, thanks for letting me know!
