### ISSUE TITLE
"Text" scitype

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#72]
How about:

```
Found
├─ Known
│  ├─ Finite
│  │  ├─ Multiclass
│  │  └─ OrderedFactor
│  ├─ Infinite
│  │  ├─ Continuous
│  │  └─ Count
│  ├─ Image
│  │  ├─ ColorImage
│  │  └─ GrayImage
|  ├─ Text
│  └─ Table
└─ Unknown
```

This could be useful for NLP. Let's say someone has one of their columns be some message, that they want to use word2vec on it (we don't yet support it but eventually should), the scitype should be something like Text right? with the basic `String => Text`. 
Then there's the `Text=>Multiclass` or even `OrderedFactor` with `categorical` for things like `["High", "Low", "Medium"]`. 

Thoughts?

**Comment by ablaom** [comment]
Good idea. Would you suggest then that scitype(::String) = Text instead of Unknown?

**Comment by tlienart** [comment]
Yes

**Comment by ablaom** [comment]
I think we will need to call this a breaking change  => minor release.

**Comment by tlienart** [comment]
yes.

Also `Text` is exported by `Base` so I went for `Textual` (?)

**Comment by ablaom** [comment]
Oh bother! Well done on "textual". I can't think of anything better.

**Comment by tlienart** [comment]
Done in  #77
