### ISSUE TITLE
More heuristics?

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#8]
Following comments on the #4 should we add keywords to `autotype` for rules such as

* ~~Consider `Int` as `Continuous`~~
* ~~Consider `Bool` as `Multiclass`~~ (already the case)
* ~~Consider `String` as `Multiclass`~~ (already the case if there are fewer than 10% etc but could force this)
* Pass a user-specified rule?

I think maybe (only?) the first one makes sense but maybe there are others?

**Comment by ablaom** [comment]
`autotype` now appears in MLJScientificTypes and not here
