### ISSUE TITLE
Why do we compress Union{T,Missing} if there are no missings?

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/ScientificTypes.jl#80]
In converting to categorical, we check whether the type is `T >: Missing` and if so  then check whether there are any true missings. If there aren't, we form a squeezed copy only of type `nonmissing(T)`. This incurs a notable overhead compared to just using `categorical` in **all cases** where `T>:Misssing`.

Note that in most case, there will be "true missings" and so we  should not  do this, but we still have to pay the price of confirming this. This is, IMO, unreasonable.

**My question**:

- Why do we  do this?

I understand it's a convenient thing  to  do but I'm not convinced it should be  ScientificTypes' responsibility. Also  I wonder where  this would occur where it would be automatically warranted to do something like it.

A case that I encountered is imputation, but if you use `FillImputer` then we already do a compression at that level so that  the  output type of the `FillImputer` is `nonmissing(T)`, see https://github.com/alan-turing-institute/MLJModels.jl/blob/8ed519f749412283d5099b662471f6686ec3e06d/src/builtins/Transformers.jl#L83-L85.

The extra case where I could see this happening is if the user does something like `dropmissing(rows)` or something like that in which  case the columns  would still be  of type `Union{T,Missing}` , but I would prefer  it if we had an **additional** functionality that did this compression `Union{T,Missing}->T`.

Several possible ways out:

- add a keyword to `coerce` like `check_missing` or  some such which would be false by default. 
- make anything that drops missing or is likely to  lead to the  problem of a vector Union{Missing,T} with no missing be such that it doesn't (e.g.: force compression after dropmissing  etc, encode all that stuff in  MLJBase). 

I would prefer (2). Of course there could be the  situation where a  user does their own stuff outside of MLJ and it  leads to the issue but then that's their responsibility. We could still  provide an additional functionality "squeezemissing" or "tighten" or whatever that does `identity.(v)` but it would  be an additional step.

Thoughts?

**Comment by ablaom** [comment]
I assume you are only speaking about the `coerce` function here. In that case, I can't think of a reason to insist on the type squeeze, and agree responsibility for this could be externalised.

**Comment by tlienart** [comment]
No, this also arises in `scitype`, consider:

```julia
function arr_scitype(A::Arr{T,N}, C::Convention, ::Val{S}) where {T,N,S}
    # no explicit scitype available
    S === nothing && return arr_scitype(A, C, S)
    # otherwise return `Arr{S,N}` but check first if the array
    # is of type Union{T,Missing}. If that's the case, check that there
    # actually **are** missing values in `A`.
    T >: Missing && has_missings(A) && return Arr{Union{S,Missing},N}
    # otherwise
    return Arr{S,N}
end
```

around line  83 of `scitype.jl`.  In the `T >: Missing` line, the second  instruction is `has_missings`; that's the instruction which checks whether there are "true missings" if not, it will  return a scitype corresponding to `nonmisssing(T)`. This makes sense but incurs a cost that I think is unreasonable (because we  have to pay it all  the time when it  only makes sense to pay it sometime)

I'll take your answer as a "go ahead" though, will propose a fix.
